jobs:
  - job: macOS
    pool:
      vmImage: macOS-10.14
    steps:
      - checkout: self
      - bash: |
          set -e
          sudo xcode-select --switch /Applications/Xcode_10.2.1.app/Contents/Developer
          brew update
          HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/ttu-capstone-podman/homebrew-podman-machine"
          mkdir -p "$HOMEBREW_TAP_DIR"
          rm -rf "$HOMEBREW_TAP_DIR"
          ln -s "$PWD" "$HOMEBREW_TAP_DIR"
          brew install podman-machine
          echo podman-machine --version
          if [[ $(podman-machine --version) -e 'podman-mchine version dev, build fb1f15e' ]]
          then
            echo "test completed successfully"
            exit 0
          fi
          exit 1

        displayName: Run Podman-install test
